quotes/authorsapp/urls.py
from django.urls import path
from . import views

app_name = 'authorsapp'

urlpatterns = [
    path('author/', views.author, name='author'),
    path('author_detail/<int:author_id>', views.detail, name='author_detail'),
]

##     <!-- {% load extract_tags %} -->
##    <!-- {{ note.tags|tags }} -->

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls')),
    path('authors/', include('authorsapp.urls')),
]

quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('quote/', views.quote, name='quote'),
    path('tag/', views.tag, name='tag'),
    path('find_tag/<str:tag_name>', views.find_tag, name='find_tag'),
    path('scrap/<str:url>', views.scrap_view, name='scrap'),
]

##             <a href="{% url 'quotesapp:delete' quote.id %}" role="button" class="contrast"> Delete note </a>

quotes/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quotesapp/models.py
from django.db import models
from django.contrib.auth.models import User
from authorsapp.models import Author

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]
    

class Quote(models.Model):
    quote = models.CharField(max_length=1500, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=1)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.quote}"
    

quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Quote, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=20, max_length=150, required=True, widget=TextInput())
    
    class Meta:
        model = Quote
        fields = ['quote']
        exclude = ['tags', 'authors']


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.core.paginator import Paginator
from django.http import HttpResponse

from .forms import QuoteForm, TagForm
from .models import Tag, Quote
from authorsapp.models import Author
from .scrapper import scrapper


# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    paginator = Paginator(quotes, 10)  # Показывать 10 цитат на каждой странице
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    top_tags = Tag.objects.annotate(num_quotes=Count('quote')*10).order_by('-num_quotes')[:10]
    return render(request, 'quotesapp/index.html', {"quotes": quotes, "top_tags": top_tags, 'page_obj': page_obj})

@login_required
def quote(request):
    tags = Tag.objects.all()
    authors = Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save(commit=False)
            new_quote.user = request.user

            authors = request.POST.get('authors')  # Предположим, что имя автора передается через форму
            author, _ = Author.objects.get_or_create(fullname=authors)
            new_quote.author = author
            new_quote.save()

            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)

            choice_authors = Author.objects.filter(fullname__in=request.POST.getlist('authors'))
            print(f"I GOT THIS AUTHORS: {choice_authors}")
            for author in choice_authors.iterator():
                new_quote.author = author

            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, 'authors': authors, 'form': form})

    return render(request, 'quotesapp/quote.html', {"tags": tags, 'authors': authors, 'form': QuoteForm()})

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            tag.user = request.user
            tag.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})

def find_tag(request, tag_name):
    quotes = Quote.objects.filter(tags__name=tag_name)
    return render(request, 'quotesapp/find_tag.html', {"quotes": quotes, "tag_name": tag_name})

def scrap_view(request, url):
    if request.user.is_authenticated and request.user.is_superuser:
        url = 'https://' + url
        print(url)
        scrapper(url)
        return HttpResponse(f'Scrapped: {url}')
    else:
        return HttpResponse('Unauthorized', status=401)

quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Go back to the main page </a></li>
        </ul>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quotesapp/templates/quotesapp/find_tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<h1> Filtering by: {{ tag_name }}</h1>

<ul>
{% for quote in quotes %}
    <li style="margin-top: 70px; padding-left: 30px;">
        <div class="quote">{{ quote.quote }}</div>
        <div style="font-size: 12px;">
            ( 
            {% for tag in quote.tags.all %}
                <a href="{% url 'quotesapp:find_tag' tag.name %}" class="outline"> {{ tag.name }} </a>
            {% endfor %}
            )
        </div>
        <div style="float: right; padding-bottom: 35px; margin-top: -20px;">
            <a href="{% url 'authorsapp:author_detail' quote.author.id %}" class="outline"> {{ quote.author.fullname }} </a>
            <div><small class="goodreads" style="font-size: 10px"><a href="{{ quote.author.goodreads_url }}" class="outline"> About {{ quote.author.fullname }} at (GoodReads) </a></small>  </div>
        </div>
        
    </li>
{% endfor %}
</ul>


{% endblock %}

quotes/quotesapp/templates/quotesapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    <link rel="stylesheet" href="static/style.css"/>
</head>
<body>
<main class="container" style="display: flexbox;">
    <div>
        <h1>Quotes to Scrape</h1>
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul style="margin-bottom: 20px; padding-left: 30px">
                <li><a href="{% url 'quotesapp:quote' %}" role="button">Add Quote</a></li>
                <li><a href="{% url 'authorsapp:author' %}" role="button">Add Author</a></li>
                <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
            </ul>
            <ul style="margin-bottom: 20px; padding-left: 30px">
                <li>Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            </ul>
            {% else %}
            <ul style="margin-bottom: 20px; padding-left: 30px">
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
        </nav>
    
    
        <ul>
        {% for quote in page_obj %}
            <li style="margin-top: 70px; padding-left: 30px;">
                <div class="quote">{{ quote.quote }}</div>
                <div style="font-size: 12px;">
                    ( 
                    {% for tag in quote.tags.all %}
                        <a href="{% url 'quotesapp:find_tag' tag.name %}" class="outline"> {{ tag.name }} </a>
                    {% endfor %}
                    )
                </div>
                <div style="float: right; padding-bottom: 35px; margin-top: -20px;">
                    <a href="{% url 'authorsapp:author_detail' quote.author.id %}" class="outline"> {{ quote.author.fullname }} </a>
                    <div><small class="goodreads" style="font-size: 10px"><a href="{{ quote.author.goodreads_url }}" class="outline"> About {{ quote.author.fullname }} at (GoodReads) </a></small>  </div>
                </div>
                
            </li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; первая</a>
                <a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
            {% endif %}
    
            <span class="current">
                Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">следующая</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
            {% endif %}
        </span>
    </div>

    <div style=" top: 0; right: 0; text-align: center; padding-right: 35px; padding-top: 255px;">
        <h2> Top 10 Tags </h2>
        {% for tag in top_tags %}
            <div> <a href="{% url 'quotesapp:find_tag' tag.name %}" class="outline" 
                style="font-size: {{ tag.num_quotes }}px; margin: 5px;"> {{ tag.name }}</a></div>
        {% endfor %}
    </div>

</main>
</body>
</html>

quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the quote:
            {{form.quote}}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select author:
            <select name="authors" required>
                {% for author in authors %}
                <option value="{{author.fullname}}">{{author.fullname}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}